### ISSUE TITLE
Tile no longer sets NR_CF_API_Password

### ISSUE THREAD

**Issue by filidav** [newrelic/newrelic-pcf-nozzle-tile#35]
[NOTE]: # tile no longer sets CF uaa admin password which causes issues if you try to reset the uaa password 

## Description
[NOTE]: # recently reset PCf uaa admin password but NR firehose app is referencing old uaa admin password.  This use to be configurable in the tile.  This is causing an issue as the app requires it at start up.

[support ticket opened with NR team

**Comment by gsanchezgavier** [comment]
Hi @filidav the tile automatically collects the following information and sets it in the necessary environment variables so that users do not need to include this information manually. These fields do not show up in the tile configuration because all of this is automatically pulled at deployment
[Here](https://github.com/newrelic/newrelic-pcf-nozzle-tile/blob/master/tile.yml#L45) are is the tile configuration of this.
