### ISSUE TITLE
Behaviour change on VMware Tanzu RabbitMQ [VMs] 2.0.5-build.12

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/newrelic-pcf-nozzle-tile#42]
Originally reported here : https://newrelic.slack.com/archives/CP2EWSX7C/p1652918372937719

TAS 2.12 and our PCF nozzle to ingest PCF metrics and logs. 
The raw metric event on the PCF side of the integration has some rabbitmq metrics that come in as 'tags' example:
`origin:"p.rabbitmq" eventType:ValueMetric timestamp:1651547607958710939 deployment:"service-instance_93ab5c31-e725-4e3b-9cd6-c2d17d411263" job:"rabbitmq-server" index:"28b0b60e-2cc8-40d2-af8e-aabf2e4fe5e2" ip:"10.223.80.54" tags:<key:"instance_id" value:"rabbit@28b0b60e-2cc8-40d2-af8e-aabf2e4fe5e2.rabbitmq-server.services.service-instance-93ab5c31-e725-4e3b-9cd6-c2d17d411263.bosh" > tags:<key:"queue" value:"betatest" > tags:<key:"source_id" value:"rabbit@localhost" > tags:<key:"vhost" value:"93ab5c31-e725-4e3b-9cd6-c2d17d411263" > valueMetric:<name:"and" value:0 unit:"" >`

On the new relic side the PCF metric event that is generated does not have this tag metric data -tags:<key:"queue" value:"betatest"
The New Relic translation just has valueMetric:<name:"rabbitmq_queue_messages_unacked" value:0
The user wants to see pcf.key= queue and value = betatest, i.e. they want the tags that decorate the PCF metric.

it changed when the user upgraded VMware Tanzu RabbitMQ [VMs] 1.21.7-build.12 to VMware Tanzu RabbitMQ [VMs] 2.0.5-build.12

**Comment by paologallinaharbur** [comment]
I have been checking the data attached and the nozzle code and as far as I understand this is no longer working since the queueName is attached as a Tag. Likely, after upgrading RabbitMQ the metric changed and the nozzle is not supporting the new format.

The integration is not adding all tags into the payload. It currently picks a fixed list of tags and attaches them to the payload depending on the envelope type:
 - EntityAttribute [code](https://github.com/newrelic/newrelic-pcf-nozzle-tile/blob/dbb09a329d2751ad7b2e2d15f79cd831c97c4527/newrelic/nrpcf/nrpcf.go#L78)
 -  HTTPattribute [code](https://github.com/newrelic/newrelic-pcf-nozzle-tile/blob/dbb09a329d2751ad7b2e2d15f79cd831c97c4527/accumulators/http/http.go#L58)
 
I'll check the payload of the past versions if available

It currently looks like a FR that could be solved including all tags to the payload. This could be problematic from the load point of view since the nozzle is already processing a huge amount of data

**Comment by paologallinaharbur** [comment]
Doing:
```
	for k, v := range e.Tags {
		et.SetAttribute(k, v)
	}

```
we can get it in the payload:
<img width="355" alt="Screen Shot 2022-07-05 at 12 58 14 PM" src="https://user-images.githubusercontent.com/43335750/177313043-c43345cc-b72a-43ce-bca2-d4f17681501d.png">

we should also consider that a behaviour like this one would increase the number of attributes and possible reach the limit per payload causing it to be completely discarded

**Comment by miransar** [comment]
Support for RabbitMQ Tags was added in version 2.7.0 of New Relic Nozzle. Closing this issue as upgrading to new version should resolve this.
